# Database
db:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/userSchema?createDatabaseIfNotExist=true
  username: root
  password: root

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl:
    auto: update

entitymanager:
  packagesToScan: com.devero
